'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  tArr: (key: string) => any[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
  en: {
    nav: {
      whyShanghai: 'Why Shanghai',
      howItWorks: 'How It Works',
      treatments: 'Treatments',
      careTeam: 'Care Team',
      trust: 'Trust',
      items: ['Why Shanghai', 'How It Works', 'Hospital Network', 'Care Team', 'Pricing', 'Blog', 'Contact'],
    },
    whyShanghai: {
      badge: 'Why Shanghai',
      title: 'World-Class Healthcare, Simplified for International Patients',
      subtitle: 'Shanghai offers access to leading hospitals, experienced specialists, transparent pricing, and personalized support for international patients.',
      stats: [
        { label: "Shanghai's Annual International Patient Visits" },
        { label: 'Public Grade-A Medical Tourism Pilots' },
        { label: 'Nationalities Served' },
        { label: 'Year-over-Year Growth' },
      ],
      healthSystem: {
        title: 'Internationally Recognized Healthcare System',
        items: [
          'Leading hospitals serving patients from around the world',
          'Dedicated international departments with English-language services',
          'Public Grade-A hospitals designated for international medical services',
          'Access to specialists across oncology, cardiology, neurology, orthopedics, fertility care, and more',
        ],
      },
      travelAccess: {
        title: 'Convenient Travel and Medical Access',
        items: [
          '240-hour visa-free transit available for travelers from many countries',
          'Medical visa support for extended treatment plans',
          'Airport pickup and transportation assistance',
          'End-to-end coordination throughout your healthcare journey',
        ],
      },
      pricing: {
        title: 'High-Quality Healthcare at Competitive Prices',
        subtitleLine1: 'Many U.S. patients still face significant out-of-pocket healthcare expenses despite having insurance coverage.',
        subtitleLine2: 'Figures reflect typical out-of-pocket costs and may vary by provider, location, insurance coverage, and treatment plan.',
        tableService: 'Service',
        tableShanghai: 'Shanghai',
        tableUs: 'Typical U.S. Cost',
        rows: [
          { service: 'Executive Health Screening', shanghai: 'From $700', us: 'From $2,500' },
          { service: 'MRI Scan', shanghai: 'From $300', us: 'From $1,000' },
          { service: 'CT Scan', shanghai: 'From $150', us: 'From $500' },
          { service: 'Specialist Consultation', shanghai: 'From $70', us: 'From $250' },
          { service: 'IVF Treatment', shanghai: 'From $4,200', us: 'From $15,000' },
          { service: 'Dental Implant', shanghai: 'From $800', us: 'From $3,000' },
        ],
        valueTitle: 'Why Patients Find Value in Shanghai',
        valueItems: [
          'Access to leading hospitals and specialists',
          'Transparent pricing before treatment',
          'Faster access to consultations, imaging, and treatment',
          'Lower out-of-pocket healthcare costs',
          'Personalized bilingual support throughout the patient journey',
        ],
        notesTitle: 'Important Notes',
        notes: [
          'Prices are provided for illustrative purposes only and do not constitute a quotation.',
          'Actual medical fees are determined by the hospital, physician, and treatment plan.',
          'U.S. pricing reflects typical self-pay costs and may vary significantly based on insurance coverage and location.',
          'Exchange rates are for reference only and may fluctuate.',
          'Complex treatments, surgeries, cancer care, and inpatient services require an individualized quotation following medical review.',
        ],
      },
    },
    processFlow: {
      badge: 'Your Journey',
      title: 'From Inquiry to Care',
      subtitle: 'A complete timeline of your medical tourism experience in Shanghai, with professional support at every step.',
      phases: [
        {
          phase: 'Before You Arrive',
          steps: [
            { title: 'Online Inquiry', description: 'AI Navigator responds instantly' },
            { title: 'Medical Assessment', description: 'Collect symptoms, recommend hospitals' },
            { title: 'Cost Estimate', description: 'Transparent pricing for consultation & basic tests' },
            { title: 'Visa & Travel', description: 'Visa-free/240h transit guidance, travel tips' },
          ],
        },
        {
          phase: 'During Your Visit',
          steps: [
            { title: 'Airport Pick-up', description: 'Trilingual nurse meets you' },
            { title: 'Hospital Visit', description: 'Nurse-accompanied consultation & tests' },
            { title: 'Treatment', description: 'World-class care at leading hospitals' },
            { title: 'Inpatient Care', description: 'Dedicated nursing support (if needed)' },
          ],
        },
        {
          phase: 'After Your Visit',
          steps: [
            { title: 'Discharge & Translation', description: 'English medical reports' },
            { title: 'Follow-up', description: 'Remote support, prescription coordination' },
          ],
        },
      ],
    },
    careTeam: {
      title: 'Trilingual Registered Nurses',
      subtitle: 'Dedicated healthcare companions at every stage of your medical journey in Shanghai.',
      badge: 'Care Team',
      expertTeam: 'Expert Care Team',
      ispnCertified: 'ISPN Certified',
      ispnDesc: 'International Standards for Professional Nurses',
      ispnIssuer: 'Certified by CGFNS (USA)',
      credentialsTitle: 'Nurse Credentials',
      servicesTitle: 'Our Nursing Services',
      nursingCare: 'Bilingual Nursing Care',
      appointmentCoordination: 'Appointment Coordination',
      translationServices: 'Translation Services',
      transportation: 'Transportation Arrangements',
      medicalReports: 'Medical Report Translation',
      emergencySupport: 'Emergency Support',
      services: [
        { title: 'Pre-Treatment Consultation', description: 'Review medical records, explain procedures, and coordinate with hospital specialists.' },
        { title: 'Appointment Scheduling', description: 'Arrange doctor consultations, diagnostic tests, and treatment sessions.' },
        { title: 'Translation & Interpretation', description: 'Real-time medical interpretation during consultations and procedures.' },
        { title: 'Hospital Navigation', description: 'Guide through admission, checkout, and payment processes.' },
        { title: 'Discharge Support', description: 'Medication instructions, follow-up appointments, and medical report translation.' },
        { title: 'Insurance Support', description: 'Provide administrative support for policy benefit checks & hospital insurance coverage confirmation' },
      ],
      credentials: [
        { name: 'Licensed Registered Nurses (RN)', detail: 'Verified by Shanghai Health Commission' },
        { name: 'Trilingual Certification', detail: 'Fluent in Japanese, English, and Chinese' },
        { name: 'JLPT N1 Certified', detail: '日本語能力試験 N1 — Japanese-Language Proficiency Test (highest level)' },
        { name: 'Medical Interpretation', detail: 'Supports medical document translation and on-site interpretation' },
        { name: 'International Patient Care', detail: '5+ years experience' },
      ],
    },
    hero: {
        badge1: 'International Insurance Hospitals',
        badge2: 'Trilingual Registered Nurses',
        badge3: '24/7 AI + Human Support',
        title: 'Healthcare in Shanghai',
        titleHighlight: 'Designed Around You',
        subtitle: "Connect with China's top hospitals, trilingual nurses, and 24/7 AI support — all through one platform.",
        cta: 'Start Your Medical Tourism',
        testimonial: "I saved $45,000 on cardiac surgery vs. the US. Bilingual nurse support made it the best medical experience ever.",
        testimonialAuthor: 'Michael T.',
        testimonialRole: 'Cardiac Surgery, USA',
      },
    testimonials: {
      title: 'What Our Patients Say',
      subtitle: 'Real stories from real patients who transformed their health journey with us.',
      patientsServed: 'Patients Served',
      countries: 'Countries',
      satisfactionRate: 'Satisfaction Rate',
      totalSavings: 'Total Savings',
      saved: 'Saved',
    },
    treatments: {
      title: 'Shanghai\'s Leading Hospitals',
      subtitle: 'Access leading hospitals across Shanghai, with recommendations tailored to your medical needs.',
      hospitalNetwork: 'Hospital Network',
      publicHospitals: 'Public Tier 1 Hospitals',
      privateHospitals: 'Private International Hospitals',
      viewAll: 'View All Hospitals',
      keyDepartments: 'Key Departments',
      certifications: 'International Certifications',
      insurance: 'Insurance:',
      all: 'All',
      modalAllHospitals: 'All Hospitals',
      modalHospitalsAvailable: 'hospitals available',
      modalAll: 'All Hospitals',
      modalPublicGradeA: 'Public Grade-A',
      modalInternationalPrivate: 'International Private',
      modalIns: 'Ins:',
    },
    howItWorks: {
      title: 'Five Simple Steps',
      subtitle: 'From your first inquiry to post-treatment follow-up, we support every step of your medical journey in Shanghai.',
      badge: 'How It Works',
      simpleProcess: 'Simple Process',
      step1Title: 'AI Consultation',
      step1Desc: 'Our AI Navigator responds instantly to understand your needs.',
      step2Title: 'Care Team Assignment',
      step2Desc: 'An experienced nurse is assigned as your care coordinator.',
      step3Title: 'Arrival in Shanghai',
      step3Desc: 'Complete support including airport transfer and hotel booking.',
      step4Title: 'Treatment & Recovery',
      step4Desc: 'Seamless integration of specialist treatment, trilingual support, and post-care follow-up.',
      steps: [
        { title: 'Submit Inquiry', description: 'Fill out our contact form with your medical needs. Our AI navigator is available 24/7.' },
        { title: 'Receive Consultation', description: 'Within 24 hours, a human coordinator provides hospital options and cost estimates.' },
        { title: 'Confirm & Travel', description: "Once you're ready to proceed, we coordinate appointments, travel logistics, and arrival support." },
        { title: 'Receive Care', description: 'Your trilingual nurse provides in-person support throughout consultations, examinations, and treatment.' },
        { title: 'Follow-Up Care', description: 'We assist with medical records, follow-up appointments, prescription coordination, and remote consultations.' },
      ],
    },
    pricing: {
      badge: 'Pricing',
      title: 'Medical Concierge Program',
      subtitle: 'Professional support tailored to your medical journey in Shanghai',
      freeTitle: 'Free Initial Consultation',
      freeDesc: 'Get started with a complimentary assessment of your medical needs',
      freeItems: [
        'Medical needs assessment',
        'Hospital & specialist recommendations',
        'Estimated medical budget',
        'Insurance direct billing guidance',
        'Shanghai healthcare system overview',
        'General patient questions',
      ],
      freeLabel: 'FREE',
      servicePricingTitle: 'Service Pricing',
      currency: 'USD',
      popularBadge: 'POPULAR',
      addonBadge: 'Add-On',
      packageBadge: 'Package',
      packages: [
        { name: 'Half-Day Add-On', duration: 'Up to 4 hours (daytime)', description: 'Only available as add-on to 3-Day / 5-Day packages' },
        { name: 'Full-Day Add-On', duration: 'Up to 8 hours (daytime)', description: 'Only available as add-on to 3-Day / 5-Day packages' },
        { name: 'Essential Care Concierge', duration: 'Up to 8 hours/day × 3 days (daytime)', description: 'Meets routine medical needs' },
        { name: 'Complex Care Concierge', duration: 'Up to 8 hours/day × 5 days (daytime)', description: 'For complex medical procedures / multi-department visits' },
      ],
      noteTitle: 'Important Note',
      noteS1: 'Half-Day Add-On and Full-Day Add-On',
      noteT1: ' are supplementary items only, and cannot be purchased separately.',
      noteS2: 'The 3-Day Standard and 5-Day Extended packages',
      noteT2: ' may be combined or extended based on your unique medical journey needs.',
      includedTitle: 'Included Services',
      includedDesc: 'Depending on your medical needs, services may include:',
      includedItems: [
        'Airport pickup or drop-off',
        'Hotel coordination assistance',
        'In-person medical accompaniment',
        'Interpretation support',
        'Medical report translation summaries',
        'Examination scheduling assistance',
        'Medication coordination support',
        'Hospital & specialist matching',
        'Transportation / payment / local guidance',
        'WeChat / WhatsApp support',
        'Visa assistance',
        'Post-Care Remote Follow-up',
      ],
      notesTitle: 'Important Notes',
      notes: [
        'Medical expenses are paid directly to hospitals or clinics.',
        'Emergency medical services are not included.',
        'Nighttime support may require additional fees.',
        'We are an independent medical concierge service, not a medical provider.',
      ],
    },
    insights: {
      badge: 'Blog',
      title: 'Latest Insights',
      subtitle: 'Discover articles about healthcare in Shanghai, medical tourism, and wellness.',
      readMore: 'Read More',
      viewAll: 'View All Articles',
      featured: '★ Featured',
    },
    blog: {
      title: 'Blog',
      subtitle: 'Discover articles about healthcare in Shanghai, medical tourism, and wellness.',
      filterContent: 'Filter Content',
      searchPlaceholder: 'Search articles...',
      search: 'Search',
      clearFilters: 'Clear filters',
      categories: 'Categories',
      popularTags: 'Popular Tags',
      noArticles: 'No articles found matching your criteria.',
      minRead: 'min read',
      previous: 'Previous',
      next: 'Next',
      home: 'Home',
      blogNav: 'Blog',
      shareLabel: 'Share:',
      previousArticle: 'Previous Article',
      nextArticle: 'Next Article',
      toc: 'Table of Contents',
      tocHide: 'Hide',
      tocShow: 'Show',
      subscribeTitle: 'Subscribe to Newsletter',
      subscribeDesc: 'Get the latest health tips and updates delivered to your inbox.',
      emailPlaceholder: 'Your email',
      subscribe: 'Subscribe',
      subscribed: '✓ Successfully subscribed! Thank you for joining our newsletter.',
      shareArticle: 'Share this article',
      subscribeSuccessTitle: 'Subscription Successful!',
      subscribeSuccessDesc: "Thank you for subscribing to our newsletter. You'll receive the latest health tips and updates.",
      close: 'Close',
      alertEmailRequired: 'Please enter your email address',
      alertSubscribeFail: 'Failed to subscribe. Please try again later.',
      alertError: 'An error occurred. Please try again later.',
      pageHeaderTitle: 'Healthcare Insights',
      pageHeaderSubtitle: 'Discover articles about medical tourism, healthcare services, and wellness tips in Shanghai',
      relatedArticles: 'Related Articles',
      recommendedHospitals: 'Recommended Hospitals',
      learnMore: 'Learn More',
      insurancePartnersLabel: 'Insurance Partners',
      bookTitle: 'Book a Free Consultation',
      bookDesc: 'Our medical coordinators are ready to assist you with hospital selection, treatment options, and travel arrangements.',
      whatsappConsult: 'WhatsApp Consultation',
      requestQuote: 'Request a Quote',
      categoryNames: {
        'health-checkups': 'Health Checkups',
        'preventive-healthcare': 'Preventive Healthcare',
        'medical-tourism': 'Medical Tourism',
        'traditional-chinese-medicine': 'Traditional Chinese Medicine',
        'shanghai-hospitals': 'Shanghai Hospitals',
        'expat-healthcare': 'Expat Healthcare',
        'patient-stories': 'Patient Stories',
        'health-guides': 'Health Guides',
      },
    },
    faq: {
      badge: 'FAQ',
      title: 'Frequently Asked Questions',
      subtitle: 'Everything you need to know about medical tourism in Shanghai.',
      items: [
        { question: 'How do I start the medical tourism process?', answer: 'Simply fill out our contact form with your medical condition and preferences. Our team will respond within 24 hours with hospital recommendations and cost estimates.' },
        { question: 'Do you help with visa applications?', answer: 'Yes, we provide visa assistance for medical treatment. For eligible countries, we can also help arrange the 240-hour transit visa-free entry to Shanghai.' },
        { question: "What if I don't speak Chinese?", answer: 'All our nurse coordinators provide real-time translation during medical consultations. Medical reports can be provided in English or your preferred language.' },
        { question: 'How do payments work?', answer: 'You pay directly to the hospital. For insurance holders, we assist with direct settlement processes.' },
        { question: 'What types of treatments do you specialize in?', answer: "We support a wide range of healthcare needs, from preventive checkups and specialist consultations to complex medical care. Every patient's needs are different. We help identify the most appropriate hospital, specialist, and care pathway for your situation." },
      ],
      stillTitle: 'Still have questions?',
      whatsappCta: 'Contact Us on WhatsApp',
    },
    contact: {
      title: 'Start Your Medical Tourism Today',
      subtitle: 'Get a free consultation from our medical team. Our AI Navigator responds instantly. Human coordinator follows up within 24 hours.',
      cta: 'Start Your Medical Tourism Today',
      badge: 'Contact',
      whatsappTitle: 'WhatsApp',
      whatsappDesc: 'AI Navigator 24/7 + Human 24h Response',
      whatsapp: 'Chat on WhatsApp',
      lineTitle: 'LINE',
      lineDesc: 'Chat directly with our coordinator',
      lineButton: 'Chat on LINE',
      lineIdLabel: 'LINE ID',
      lineId: 'sara_shanghaimed',
      lineScanHint: 'Scan the QR code to add us on LINE',
      lineQrAlt: 'LINE QR Code',
      locationLabel: 'Location',
      locationValue: "Shanghai, People's Republic of China",
      responseLabel: 'Response Time',
      responseValue: 'AI: Instant | Human: Within 24 hours',
      emailLabel: 'Email',
      nameLabel: 'Full Name *',
      namePlaceholder: 'Your full name',
      emailLabel2: 'Email *',
      emailPlaceholder: 'your@email.com',
      countryLabel: 'Country *',
      countryPlaceholder: 'Select your country *',
      otherCountry: 'Other',
      otherCountryPlaceholder: 'Enter your country *',
      countries: {
        'United States': 'United States',
        'United Kingdom': 'United Kingdom',
        'Canada': 'Canada',
        'Australia': 'Australia',
        'Japan': 'Japan',
        'South Korea': 'South Korea',
        'Singapore': 'Singapore',
        'Germany': 'Germany',
        'France': 'France',
      },
      phoneLabel: 'Phone / WhatsApp',
      phonePlaceholder: 'Phone / WhatsApp (optional)',
      medicalNeedsLabel: 'Medical Needs *',
      medicalNeedsPlaceholder: 'Select your medical need',
      medicalNeeds: {
        consultation: 'Medical Consultation',
        cardiology: 'Cardiology',
        neurology: 'Neurology',
        oncology: 'Oncology',
        orthopedics: 'Orthopedics',
        checkup: 'Health Check-up',
        dental: 'Dental Care',
        plastic: 'Plastic Surgery',
        other: 'Other',
      },
      messageLabel: 'Your Message',
      messagePlaceholder: 'Please describe your medical condition or inquiry...',
      submit: 'Get Free Consultation',
      submitting: 'Sending...',
      successTitle: 'Thank You!',
      successMessage: "Thank you! Our AI Navigator has received your inquiry and our team will follow up within 24 hours. You can also reach us on WhatsApp — we'll respond as soon as possible.",
      sendAnother: 'Send Another Message',
      privacyNote: 'By submitting this form, you agree to our Privacy Policy and consent to being contacted about our medical services.',
      alertFail: 'Failed to send message. Please try again or contact us via WhatsApp.',
    },
    footer: {
      tagline: 'Connecting international patients with Shanghai\'s world-class medical institutions and bilingual healthcare professionals.',
      columns: [
        {
          title: 'About',
          links: ['About Us', 'Why Shanghai', 'Our Network', 'Care Team'],
        },
        {
          title: 'Treatments',
          links: ['Hospitals', 'Specialties', 'Pricing Guide'],
        },
        {
          title: 'Support',
          links: ['How It Works', 'FAQ', 'Contact Us', 'WhatsApp Support'],
        },
        {
          title: 'Legal',
          links: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'Medical Disclaimer'],
        },
      ],
      rights: 'All rights reserved.',
      location: 'Shanghai, China',
    },
    agentChat: {
      welcome: "Hello! I'm Navi, your medical navigator. Ask me anything about hospitals, treatments, costs, visas, or planning your medical journey in Shanghai.",
      questions: [
        "What's included in your personalized service?",
        'How do I book an appointment?',
        "What's the cost of your one-on-one service?",
      ],
      inputPlaceholder: 'Ask me about healthcare in Shanghai...',
      chatTitle: 'Navi · Medical Navigator',
      chatSubtitle: '24/7 AI assistant',
    },
    pages: {
      treatmentsTitle: 'Treatments & Hospitals',
      treatmentsSubtitle: "Access to Shanghai's finest medical institutions across all specialties.",
      contactTitle: 'Contact Us',
      contactSubtitle: 'Get started with your medical journey today. Our team is ready to help 24/7.',
      patientStoriesTitle: 'Patient Stories',
      patientStoriesSubtitle: 'Real experiences from patients who trusted us with their health.',
      whyShanghaiTitle: 'Why Shanghai?',
      whyShanghaiSubtitle: 'Shanghai has emerged as a premier destination for international patients seeking world-class medical care at accessible prices.',
      careTeamTitle: 'Our Care Team',
      careTeamSubtitle: 'ISPN-certified trilingual nurses dedicated to your health and comfort.',
      howItWorksTitle: 'How It Works',
      howItWorksSubtitle: 'Our streamlined process makes it easy to access world-class medical care in Shanghai.',
      faqTitle: 'Frequently Asked Questions',
      faqSubtitle: 'Everything you need to know about receiving medical care in Shanghai — costs, hospital quality, visas, insurance, and bilingual support.',
    },
  },
  ja: {
    nav: {
      whyShanghai: 'なぜ上海か',
      howItWorks: '仕組み',
      treatments: '治療',
      careTeam: 'ケアチーム',
      trust: '信頼',
      items: ['なぜ上海か', 'ご利用の流れ', '病院ネットワーク', 'ケアチーム', '料金', 'ブログ', 'お問い合わせ'],
    },
    whyShanghai: {
      badge: 'なぜ上海か',
      title: '国際患者のための、シンプルで世界クラスの医療',
      subtitle: '上海では、一流病院へのアクセス、経験豊富な専門医、透明な料金体系、そして国際患者向けのきめ細かなサポートをご提供しています。',
      stats: [
        { label: '上海の年間国際患者受入数' },
        { label: '医療ツーリズム指定公立病院' },
        { label: '対応国籍数' },
        { label: '前年比成長率' },
      ],
      healthSystem: {
        title: '国際的に認められた医療体制',
        items: [
          '世界中から患者を受け入れる一流病院',
          '英語対応の国際医療部門を完備',
          '国際医療サービスに指定された公立三級甲等病院',
          'がん・循環器・神経・整形・不妊治療など、各分野の専門医へのアクセス',
        ],
      },
      travelAccess: {
        title: '快適な渡航と円滑な医療アクセス',
        items: [
          '多くの国から240時間（10日間）の通過ビザ免除での渡航が可能',
          '長期治療プランに対応した医療ビザのサポート',
          '空港送迎・移動のサポート',
          '医療の旅全体を通じたトータルコーディネート',
        ],
      },
      pricing: {
        title: '競争力のある価格で高品質な医療を',
        subtitleLine1: '米国の患者は、保険に加入していても高額な自己負担に直面することが少なくありません。',
        subtitleLine2: '記載の金額は典型的な自己負担額の目安であり、医療機関・地域・保険内容・治療プランにより異なります。',
        tableService: '診療項目',
        tableShanghai: '上海',
        tableUs: '米国の典型価格',
        rows: [
          { service: 'エグゼクティブ健康診断', shanghai: '$700〜', us: '$2,500〜' },
          { service: 'MRI検査', shanghai: '$300〜', us: '$1,000〜' },
          { service: 'CT検査', shanghai: '$150〜', us: '$500〜' },
          { service: '専門医診察', shanghai: '$70〜', us: '$250〜' },
          { service: '不妊治療（IVF）', shanghai: '$4,200〜', us: '$15,000〜' },
          { service: 'インプラント治療', shanghai: '$800〜', us: '$3,000〜' },
        ],
        valueTitle: '患者が上海に価値を見出す理由',
        valueItems: [
          '一流病院と専門医へのアクセス',
          '治療前の透明な料金提示',
          '診察・検査・治療への迅速なアクセス',
          'より低い自己負担医療費',
          '治療の旅全体を通じたバイリンガルのパーソナルサポート',
        ],
        notesTitle: '重要事項',
        notes: [
          '価格は参考情報であり、見積りを構成するものではありません。',
          '実際の医療費は、病院・医師・治療プランにより決定されます。',
          '米国の価格は典型的な自己負担額を反映したものであり、保険内容や地域により大きく異なる場合があります。',
          '為替レートは参考値であり、変動する場合があります。',
          '複雑な治療、手術、がん治療、入院サービスには、医学的審査後の個別見積りが必要です。',
        ],
      },
    },
    processFlow: {
      badge: 'あなたの医療の旅',
      title: 'お問い合わせから治療まで',
      subtitle: '上海での医療ツーリズム体験の完全なタイムライン。各段階で専門スタッフがサポートします。',
      phases: [
        {
          phase: '到着前',
          steps: [
            { title: 'オンライン問い合わせ', description: 'AIナビゲーターが即時対応' },
            { title: '医療アセスメント', description: '症状を確認し、病院をご提案' },
            { title: '費用見積り', description: '診察・基本検査の透明な価格提示' },
            { title: 'ビザ・渡航', description: 'ビザなし・240時間通過案内、渡航のコツ' },
          ],
        },
        {
          phase: '滞在中',
          steps: [
            { title: '空港送迎', description: '三か国語対応の看護師がお迎え' },
            { title: '病院受診', description: '看護師同行による診察・検査' },
            { title: '治療', description: '一流病院での世界クラスの治療' },
            { title: '入院治療', description: '専任の看護サポート（必要に応じて）' },
          ],
        },
        {
          phase: '帰国後',
          steps: [
            { title: '退院・翻訳', description: '英語の診療レポート' },
            { title: 'フォローアップ', description: '遠隔サポート・処方調整' },
          ],
        },
      ],
    },
    careTeam: {
      title: '三か国語対応の登録看護師',
      subtitle: '上海での医療の旅の各段階における専任のヘルスケアコンパニオン。',
      badge: 'ケアチーム',
      expertTeam: '専門ケアチーム',
      ispnCertified: 'ISPN認定',
      ispnDesc: '国際看護師基準',
      ispnIssuer: 'CGFNS（米国）認定',
      credentialsTitle: '看護師の資格',
      servicesTitle: '看護サービス',
      nursingCare: '三か国語対応看護',
      appointmentCoordination: '予約調整',
      translationServices: '通訳サービス',
      transportation: '交通手配',
      medicalReports: '医療レポートの翻訳',
      emergencySupport: '緊急時サポート',
      services: [
        { title: '治療前カウンセリング', description: '診療記録の確認、治療内容の説明、病院の専門医との連携調整。' },
        { title: '予約手配', description: '医師の診察、各種検査、治療セッションの手配。' },
        { title: '通訳・翻訳', description: '診察や処置中のリアルタイム医療通訳。' },
        { title: '病院内サポート', description: '受付・会計・お支払い手続きのご案内。' },
        { title: '退院サポート', description: '服薬指導、フォローアップ予約、診療レポートの翻訳。' },
        { title: '保険サポート', description: '保険給付内容の確認・病院での保険適用確認の事務サポート' },
      ],
      credentials: [
        { name: '登録看護師（RN）ライセンス', detail: '上海市衛生健康委員会認証' },
        { name: '三か国語認定', detail: '日本語・英語・中国語に堪能' },
        { name: '日本語能力試験N1（JLPT N1）', detail: '日本語能力試験の最高レベル（N1）認定' },
        { name: '医療通訳', detail: '医療文書の翻訳・対面通訳に対応' },
        { name: '国際患者ケア', detail: '5年以上の経験' },
      ],
    },
    hero: {
      badge1: '47の国際保険直接支払い病院',
      badge2: '日本語・英語・中国語対応の看護師',
      badge3: '24時間AIナビゲーター + 人間によるフォローアップ',
      title: '上海の世界クラスの医療。',
      titleHighlight: 'コストはわずか。',
      subtitle: '中国のトップ病院、日本語・英語・中国語対応の看護師、24時間AIサポートを一つのプラットフォームで。',
      cta: '今日から医療ツーリズムを始めましょう',
      testimonial: '心臓手術で米国と比較して45,000ドル節約できました。バイリンガル看護師が一歩一歩付き添ってくれました。最高の医療体験でした。',
      testimonialAuthor: 'Michael T.',
      testimonialRole: '心臓手術患者、米国',
    },
    treatments: {
      title: '上海のトップ医療機関',
      subtitle: '医療ニーズに合わせたご提案とともに、上海の一流病院へのアクセスをご提供します。',
      hospitalNetwork: '病院ネットワーク',
      publicHospitals: '公立三級甲等病院',
      privateHospitals: '国際民間病院',
      viewAll: '全病院を表示',
      keyDepartments: '重点科室',
      certifications: '国際認証',
      insurance: '保険:',
      all: '全て',
      modalAllHospitals: 'すべての病院',
      modalHospitalsAvailable: '病院が利用可能',
      modalAll: 'すべて',
      modalPublicGradeA: '公立三級甲等',
      modalInternationalPrivate: '国際民間',
      modalIns: '保険:',
    },
    howItWorks: {
      title: '仕組み',
      subtitle: '最初のお問い合わせから完全回復まで、上海での医療ツーリズムの各段階をサポートします。',
      badge: 'ご利用の流れ',
      simpleProcess: 'シンプルなプロセス',
      step1Title: 'AIによる問診',
      step1Desc: 'AIナビゲーターが即座に応答し、あなたのニーズを理解します。',
      step2Title: '医療チームの割り当て',
      step2Desc: '経験豊富な看護師がケアコーディネーターとして同行します。',
      step3Title: '上海への到着',
      step3Desc: '空港から病院までの移動手配、ホテル予約を含む完全なサポート。',
      step4Title: '治療とリカバリー',
      step4Desc: '専門医の治療、三か国語対応サポート、術後ケアの完璧な統合。',
      steps: [
        { title: 'お問い合わせ', description: 'ご病状やご希望をフォームにてお送りください。AIナビゲーターが24時間365日対応します。' },
        { title: '相談内容の受取', description: '24時間以内に担当コーディネーターが病院のご提案と費用見積りをお届けします。' },
        { title: '確定・渡航', description: 'ご出発が確定したら、予約手配・渡航手配・到着時サポートを調整します。' },
        { title: '治療の受入', description: '日本語・英語・中国語対応の看護師が診察・検査・治療全般にわたり対面でサポートします。' },
        { title: 'アフターケア', description: '診療記録、フォローアップ予約、処方調整、オンライン診療をサポートします。' },
      ],
    },
    pricing: {
      badge: '料金',
      title: 'メディカルコンシェルジュプログラム',
      subtitle: '上海での医療の旅に合わせたプロフェッショナルサポート',
      freeTitle: '初回相談無料',
      freeDesc: '医療ニーズの無料アセスメントから始めましょう',
      freeItems: [
        '医療ニーズの評価',
        '病院・専門医のご提案',
        '医療予算の見積り',
        '保険直接請求（ダイレクトビリング）の案内',
        '上海の医療制度の概要',
        '患者様からのご質問全般',
      ],
      freeLabel: '無料',
      servicePricingTitle: 'サービス料金',
      currency: 'USD',
      popularBadge: '人気',
      addonBadge: '追加',
      packageBadge: 'パッケージ',
      packages: [
        { name: '半日追加オプション', duration: '4時間まで（日中）', description: '3日間・5日間パッケージへの追加オプション専用です' },
        { name: '1日追加オプション', duration: '8時間まで（日中）', description: '3日間・5日間パッケージへの追加オプション専用です' },
        { name: 'エッセンシャルケアコンシェルジュ', duration: '1日8時間まで × 3日間（日中）', description: '定期的な医療ニーズに対応' },
        { name: 'コンプレックスケアコンシェルジュ', duration: '1日8時間まで × 5日間（日中）', description: '複雑な治療・複数診療科の受診に対応' },
      ],
      noteTitle: '重要事項',
      noteS1: '半日追加オプション・1日追加オプション',
      noteT1: 'は追加専用アイテムであり、単体ではご購入いただけません。',
      noteS2: '3日間スタンダード・5日間エクステンデッドの各パッケージ',
      noteT2: 'は、お客様の医療の旅のニーズに合わせて組み合わせや延長が可能です。',
      includedTitle: '含まれるサービス',
      includedDesc: '医療ニーズに応じて、以下のサービスが含まれます：',
      includedItems: [
        '空港送迎（到着時・出発時）',
        'ホテル手配サポート',
        '対面での医療同行',
        '通訳サポート',
        '診療レポート翻訳のサマリー',
        '検査予約のサポート',
        'お薬手配のサポート',
        '病院・専門医のマッチング',
        '移動・お支払い・現地案内',
        'WeChat / LINE サポート',
        'ビザサポート',
        'アフターケアの遠隔フォローアップ',
      ],
      notesTitle: '重要事項',
      notes: [
        '医療費は病院またはクリニックへ直接お支払いいただきます。',
        '緊急医療サービスは含まれません。',
        '夜間サポートには追加料金がかかる場合があります。',
        '当社は独立系の医療コンシェルジュサービスであり、医療機関ではありません。',
      ],
    },
    insights: {
      badge: 'ブログ',
      title: '最新のインサイト',
      subtitle: '上海の医療、医療ツーリズム、ウェルネスに関する記事をご覧ください。',
      readMore: '続きを読む',
      viewAll: 'すべての記事を見る',
      featured: '★ 注目',
    },
    blog: {
      title: 'ブログ',
      subtitle: '上海の医療、医療ツーリズム、ウェルネスに関する記事をご覧ください。',
      filterContent: '絞り込み',
      searchPlaceholder: '記事を検索...',
      search: '検索',
      clearFilters: '条件をクリア',
      categories: 'カテゴリー',
      popularTags: '人気のタグ',
      noArticles: '条件に一致する記事が見つかりませんでした。',
      minRead: '分',
      previous: '前へ',
      next: '次へ',
      home: 'ホーム',
      blogNav: 'ブログ',
      shareLabel: 'シェア：',
      previousArticle: '前の記事',
      nextArticle: '次の記事',
      toc: '目次',
      tocHide: '隠す',
      tocShow: '表示',
      subscribeTitle: 'ニュースレター購読',
      subscribeDesc: '最新の健康情報とお知らせをメールでお届けします。',
      emailPlaceholder: 'メールアドレス',
      subscribe: '購読する',
      subscribed: '✓ ご購読ありがとうございます。ニュースレターに登録されました。',
      shareArticle: 'この記事をシェア',
      subscribeSuccessTitle: '購読完了！',
      subscribeSuccessDesc: 'ニュースレターのご購読ありがとうございます。最新の健康情報をお届けします。',
      close: '閉じる',
      alertEmailRequired: 'メールアドレスを入力してください',
      alertSubscribeFail: '購読に失敗しました。しばらくしてからもう一度お試しください。',
      alertError: 'エラーが発生しました。しばらくしてからもう一度お試しください。',
      pageHeaderTitle: 'ヘルスケアインサイト',
      pageHeaderSubtitle: '上海の医療ツーリズム、医療サービス、ウェルネスに関する記事をご覧ください',
      relatedArticles: '関連記事',
      recommendedHospitals: 'おすすめ病院',
      learnMore: '詳しく見る',
      insurancePartnersLabel: '提携保険',
      bookTitle: '無料相談を予約する',
      bookDesc: '病院選び、治療プラン、渡航手配まで、医療コーディネーターが全面的にサポートします。',
      whatsappConsult: 'LINEで相談',
      requestQuote: '見積りを依頼',
      categoryNames: {
        'health-checkups': '健康診断',
        'preventive-healthcare': '予防医療',
        'medical-tourism': '医療ツーリズム',
        'traditional-chinese-medicine': '伝統中国医学',
        'shanghai-hospitals': '上海の病院',
        'expat-healthcare': '駐在員医療',
        'patient-stories': '患者の声',
        'health-guides': '健康ガイド',
      },
    },
    faq: {
      badge: 'よくある質問',
      title: 'よくある質問',
      subtitle: '上海での医療ツーリズムについて知っておくべきすべてのこと。',
      items: [
        { question: '医療ツーリズムはどのように始めればよいですか？', answer: 'お問い合わせフォームにご病状とご希望をご記入いただくだけです。24時間以内に、病院のご提案と費用見積りをお返しします。' },
        { question: 'ビザ申請のサポートはありますか？', answer: 'はい、治療目的のビザサポートをご提供しています。対象国の方には、上海への240時間通過ビザ免除での入国手配もお手伝いできます。' },
        { question: '中国語が話せない場合はどうなりますか？', answer: 'すべての看護コーディネーターが診察時にリアルタイム通訳をご提供します。診療レポートは英語またはご希望の言語でお届けできます。' },
        { question: 'お支払いはどのように行いますか？', answer: '医療費は病院へ直接お支払いいただきます。保険をお持ちの方には、直接精算（ダイレクトビリング）の手続きをお手伝いします。' },
        { question: 'どのような治療に対応していますか？', answer: '健康診断や専門医の診察から複雑な治療まで、幅広い医療ニーズに対応しています。患者様一人ひとりのニーズは異なりますので、最適な病院・専門医・ケアプランをご提案します。' },
      ],
      stillTitle: 'まだご不明な点はありますか？',
      whatsappCta: 'LINEで問い合わせる',
    },
    contact: {
      title: '今日から医療ツーリズムを始めましょう',
      subtitle: '医療チームによる無料相談を受けることができます。AIナビゲーターが即時に応答し、担当コーディネーターが24時間以内にフォローアップします。',
      cta: '今日から医療ツーリズムを始めましょう',
      badge: 'お問い合わせ',
      whatsappTitle: 'WhatsApp',
      whatsappDesc: 'AIナビゲーター24時間＋人間による24時間対応',
      whatsapp: 'WhatsAppでチャット',
      lineTitle: 'LINE',
      lineDesc: 'コーディネーターが直接ご対応いたします',
      lineButton: 'LINEで相談する',
      lineIdLabel: 'LINE ID',
      lineId: 'sara_shanghaimed',
      lineScanHint: 'QRコードをスキャンして友だち追加',
      lineQrAlt: 'LINE QRコード',
      locationLabel: '所在地',
      locationValue: '中華人民共和国 上海市',
      responseLabel: '応答時間',
      responseValue: 'AI：即時｜担当者：24時間以内',
      emailLabel: 'メール',
      nameLabel: 'お名前 *',
      namePlaceholder: 'お名前をご記入ください',
      emailLabel2: 'メールアドレス *',
      emailPlaceholder: 'your@email.com',
      countryLabel: 'お住まいの国 *',
      countryPlaceholder: 'お住まいの国を選択してください *',
      otherCountry: 'その他',
      otherCountryPlaceholder: '国名をご記入ください *',
      countries: {
        'United States': 'アメリカ',
        'United Kingdom': 'イギリス',
        'Canada': 'カナダ',
        'Australia': 'オーストラリア',
        'Japan': '日本',
        'South Korea': '韓国',
        'Singapore': 'シンガポール',
        'Germany': 'ドイツ',
        'France': 'フランス',
      },
      phoneLabel: '電話 / LINE',
      phonePlaceholder: '電話 / LINE（任意）',
      medicalNeedsLabel: '医療ニーズ *',
      medicalNeedsPlaceholder: '医療ニーズを選択してください',
      medicalNeeds: {
        consultation: '一般診察',
        cardiology: '循環器内科',
        neurology: '神経内科',
        oncology: '腫瘍科',
        orthopedics: '整形外科',
        checkup: '健康診断',
        dental: '歯科治療',
        plastic: '形成外科',
        other: 'その他',
      },
      messageLabel: 'メッセージ',
      messagePlaceholder: 'ご病状やお問い合わせ内容をご記入ください...',
      submit: '無料相談を申し込む',
      submitting: '送信中...',
      successTitle: 'ありがとうございます！',
      successMessage: 'お問い合わせを受け付けました。AIナビゲーターが確認し、担当チームが24時間以内にフォローアップいたします。今すぐのご相談はLINEでも承ります。',
      sendAnother: '別のメッセージを送信',
      privacyNote: 'このフォームを送信することで、プライバシーポリシーに同意し、弊社の医療サービスに関するご連絡に同意したものとみなされます。',
      alertFail: 'メッセージの送信に失敗しました。もう一度お試しいただくか、LINEでご連絡ください。',
    },
    footer: {
      tagline: '国際患者と、上海の世界クラスの医療機関・バイリンガル医療スタッフをつなぐ。',
      columns: [
        {
          title: '会社情報',
          links: ['会社概要', 'なぜ上海か', '病院ネットワーク', 'ケアチーム'],
        },
        {
          title: '治療',
          links: ['病院', '診療科', '料金ガイド'],
        },
        {
          title: 'サポート',
          links: ['ご利用の流れ', 'よくある質問', 'お問い合わせ', 'LINEサポート'],
        },
        {
          title: '法的事項',
          links: ['プライバシーポリシー', '利用規約', 'クッキーポリシー', '医療免責事項'],
        },
      ],
      rights: 'All rights reserved.',
      location: '上海（中国）',
    },
    hospitals: {
      huashan: {
        description: '全国の皮膚科・脳神経外科で第1位。中国で最も国際的に認知された病院の一つです。',
        specialties: ['脳神経外科', '皮膚科', '感染症科'],
      },
      'children-fudan': {
        description: '新生児医療と小児希少疾患の中心病院です。',
        specialties: ['新生児科', '小児外科', '集中治療科'],
      },
      ruijin: {
        description: '骨髄移植とCAR-T療法のパイオニア。世界トップクラスの治療成績を誇ります。',
        specialties: ['血液内科', '内分泌内科', '熱傷・創傷治療'],
      },
      'shanghai-general': {
        description: '上海で最も歴史ある名門病院の一つ。眼科・泌尿器科が国内屈指の水準です。',
        specialties: ['眼科', '泌尿器科', '耳鼻咽喉科・頭頸部外科'],
      },
      zhongshan: {
        description: '復旦大学附属。循環器医療の中心で、独立した国際患者棟と英語対応スタッフを完備しています。',
        specialties: ['一般外科', '消化器内科', '循環器内科'],
      },
      renji: {
        description: '上海交通大学附属。消化器内科は4年連続全国第1位。肝移植の中心病院です。',
        specialties: ['消化器内科', '生殖医学', '膠原病・リウマチ科'],
      },
      longhua: {
        description: '伝統中国医学（TCM）の頂点。TCM医療ツーリズム公式指定病院。鍼灸・漢方療法・リハビリテーションをご提供します。',
        specialties: ['中医腫瘍科', '中医整形外科', '中医外科'],
      },
      ipmch: {
        description: '中国福利会附属。ハイリスク妊娠・胎児医学・生殖医学の中心病院です。',
        specialties: ['生殖医学', '産科', '婦人科'],
      },
      scmc: {
        description: '上海交通大学附属。中国トップクラスの小児心臓外科。Project HOPEと提携しています。',
        specialties: ['小児心臓外科', '小児血液腫瘍科', '発達行動小児科'],
      },
      sixth: {
        description: '1963年に世界初の断肢再植手術を成功。国際的に評価される整形外科・内分泌内科の中心です。',
        specialties: ['整形外科', '内分泌代謝科', 'スポーツ医学'],
      },
      'first-maternity': {
        description: '上海屈指の産婦人科病院。産科・新生児医療を国際患者サポート付きでご提供します。',
        specialties: ['産科', '胎児医学', '生殖医学'],
      },
      xinhua: {
        description: '脊椎外科・小児外科の中心。国際サービスを完備しています。',
        specialties: ['小児科', '皮膚科', '一般外科'],
      },
      huadong: {
        description: '復旦大学附属。老年医学・リハビリテーションの名門。エグゼクティブ健診で人気です。',
        specialties: ['老年医学', 'リハビリテーション科', '臨床栄養科'],
      },
      ninth: {
        description: '中国第1位の歯科病院。2024年1月に浦東キャンパスへ国際医療部を開設。100台超の診療ユニット・CBCT・マイクロスコープ・レーザー設備を完備。常駐の国際インプラント専門医と、複雑症例へのMDT体制を整えています。40か国以上の患者の治療実績があります。',
        specialties: ['歯科口腔外科 第1位', '形成・再建外科', '顎顔面外科'],
      },
      jiahui: {
        description: '上海最大級の民営国際病院（500床）。マサチューセッツ総合病院提携のフルサービス医療センターです。',
        specialties: ['腫瘍科', '外科', '総合診療科'],
      },
      unicare: {
        description: 'Chindex Healthcareグループ。西洋式の患者ケアと国際基準に基づく総合医療を提供します。',
        specialties: ['家庭医学', '産科', '小児科'],
      },
      parkway: {
        description: '世界最大級の医療グループ IHH Healthcare の一員。プルーデンシャル直結精算など保険ネットワークが充実しています。',
        specialties: ['多診療科', '家庭医学', '診断科'],
      },
      shine: {
        description: 'Mayo Clinic Care Network 加盟病院。循環器・消化器・総合診療を国際基準でご提供します。',
        specialties: ['循環器内科', '消化器内科', '総合診療科'],
      },
      raffles: {
        description: 'シンガポール Surbana Jurong グループ。医療ツーリズムと総合健診サービスが中心です。',
        specialties: ['エグゼクティブ健診', '総合診療科', '医療ツーリズム'],
      },
    },
    agentChat: {
      welcome: 'こんにちは！私はNavi、あなたの医療ナビゲーターです。病院、治療、費用、ビザ、上海での医療の旅の計画について、何でもお尋ねください。',
      questions: [
        'パーソナライズドサービスには何が含まれますか？',
        '予約はどのように取ればよいですか？',
        '個人対応サービスの料金はいくらですか？',
      ],
      inputPlaceholder: '上海の医療について何でもお尋ねください...',
      chatTitle: 'Navi・医療ナビゲーター',
      chatSubtitle: '24時間AIアシスタント',
    },
    pages: {
      treatmentsTitle: '治療と病院',
      treatmentsSubtitle: 'あらゆる診療科における、上海の最高水準の医療機関へのアクセス。',
      contactTitle: 'お問い合わせ',
      contactSubtitle: '今日からあなたの医療の旅を始めましょう。チームが24時間体制でサポートします。',
      patientStoriesTitle: '患者の声',
      patientStoriesSubtitle: '私たちに健康を託された患者様の実際の体験談。',
      whyShanghaiTitle: 'なぜ上海なのか？',
      whyShanghaiSubtitle: '上海は、手の届く価格で世界クラスの医療を求める国際患者にとって、屈指の渡航先となっています。',
      careTeamTitle: '私たちのケアチーム',
      careTeamSubtitle: 'ISPN認定の三か国語対応看護師が、あなたの健康と安らぎのために尽力します。',
      howItWorksTitle: 'ご利用の流れ',
      howItWorksSubtitle: 'シンプルなプロセスで、上海の世界クラスの医療にアクセスできます。',
      faqTitle: 'よくある質問',
      faqSubtitle: '上海での医療受け入れについて知っておくべきこと — 費用、病院の質、ビザ、保険、バイリンガルサポート。',
    },
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  // SSR 安全模式：初始渲染固定 'en'，保证服务端 HTML 与客户端首次渲染一致（避免 React 水合错误）
  const [language, setLanguageState] = useState<Language>('en')

  // 挂载完成后从 localStorage 恢复用户语言偏好
  useEffect(() => {
    const saved = localStorage.getItem('shanghaimed-lang')
    if (saved === 'en' || saved === 'ja') {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('shanghaimed-lang', lang)
      document.documentElement.lang = lang
    }
  }

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const resolveKey = (key: string): any => {
    const keys = key.split('.')
    let value: any = translations[language]
    for (const k of keys) {
      value = value?.[k]
    }
    return value
  }

  const t = (key: string): string => {
    const value = resolveKey(key)
    return typeof value === 'string' ? value : key
  }

  // 数组翻译：返回数组数据（如 FAQ 列表、流程步骤等），找不到时返回空数组供组件回退到英文常量
  const tArr = (key: string): any[] => {
    const value = resolveKey(key)
    return Array.isArray(value) ? value : []
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tArr }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
